=== pme123/scala-adapters/server/test/resources/testdata/af_input_new.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Simple Types -->
    <xs:simpleType name="afType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="color"/>
            <xs:enumeration value="short_text"/>
            <xs:enumeration value="long_text"/>
            <xs:enumeration value="image"/>
            <xs:enumeration value="video"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="number"/>
            <xs:enumeration value="date" />
            <xs:enumeration value="time"/>
            <xs:enumeration value="dropdown"/>
            <xs:enumeration value="timing"/>
            <xs:enumeration value="animation_factory"/>
            <xs:enumeration value="dynamic_import"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- definition of simple attributes -->
    <xs:attribute name="isConfigurable" type="xs:boolean" default="false"/>
    <xs:attribute name="ident" type="xs:string"/>
    <xs:attribute name="type" type="afType"/>
    <xs:attribute name="isHidden" type="xs:boolean" default="false"/>
    <xs:attribute name="isReadOnly" type="xs:boolean" default="false"/>
    <xs:attribute name="defaultValue" type="xs:string"/>
    <xs:attribute name="title" type="xs:string"/>
    <xs:attribute name="info" type="xs:string"/>
    <xs:attribute name="isDefault" type="xs:boolean" default="false"/>
    <xs:attribute name="language" type="xs:string" default="de"/>
    <!-- definition of simple elements -->


    <!-- definition of complex elements -->
    <xs:element name="InputAF">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="MovieVars" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="DataSets" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute ref="isConfigurable" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="MovieVars">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ValueSet" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="DataSets">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ValueSet" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ValueSet">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ValueEntry" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="ValueSet" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute ref="ident" use="required"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="isHidden" use="optional"/>
            <xs:attribute ref="isReadOnly" use="optional"/>
            <xs:attribute ref="defaultValue" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ValueEntry">
        <xs:complexType>
            <xs:attribute ref="language" use="required"/>
            <xs:attribute ref="title" use="required"/>
            <xs:attribute ref="info" use="optional"/>
            <xs:attribute ref="isDefault" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="DropDown">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ValueSet" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pme123/scala-adapters/server/test/resources/testdata/af_input_new.xml
<?xml version="1.0" encoding="UTF-8" ?>
<InputAF xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="af_input_new.xsd"
	isConfigurable="true">
	<MovieVars>
		<ValueSet ident="batchinterval" type="number" defaultValue="10000" isHidden="true">
			<ValueEntry language="en" title="Batch Interval" info="Time of one batch" isDefault="true" />
			<ValueEntry language="de" title="Dataset Dauer" info="Dauer einer Seite" />
		</ValueSet>
		<ValueSet ident="itemsperbatch" type="number" defaultValue="1" isReadOnly="true">
			<ValueEntry language="en" title="Items per batch" info="Number of datasets per batch" isDefault="true" />
			<ValueEntry language="de" title="Anzahl Datasets" info="Anzahl Datasets pro Seite" />
		</ValueSet>
		<ValueSet ident="slogan" type="short_text" defaultValue="The Slogan is good">
			<ValueEntry language="en" title="Company's slogan" info="Your company's slogan" isDefault="true" />
			<ValueEntry language="de" title="Firmen-Slogan" info="Ihr Firmen-Slogan" />
		</ValueSet>
		<ValueSet ident="logo" type="image" defaultValue="32144.jpg">
			<ValueEntry language="en" title="Company's logo" info="Choice of the company logo" isDefault="true" />
			<ValueEntry language="de" title="Firmen-Logo" info="Auswahl des Firmenlogos" />
		</ValueSet>
		<ValueSet ident="advertiseVideo" type="video" defaultValue="32144.flv">
			<ValueEntry language="en" title="Advertising video" info="Advertising video as .flv" isDefault="true" />
			<ValueEntry language="de" title="Werbevideo" info="Werbevidio als .flv" />
		</ValueSet>
		<ValueSet ident="hasBackground" type="boolean" defaultValue="true">
			<ValueEntry language="en" title="Background" info="Text description" isDefault="true" />
			<ValueEntry language="de" title="Hintergrund" info="Textbeschreibung" />
		</ValueSet>
		<ValueSet ident="bgColor" type="color" defaultValue="0">
			<ValueEntry language="en" title="Background color" info="Color of the background" isDefault="true" />
			<ValueEntry language="de" title="Hintergrundfarbe" info="Farbe des Hintergrundes" />
		</ValueSet>
		<ValueSet ident="timing" type="timing">
			<ValueEntry language="en" title="Timing" info="Create Timings here" isDefault="true" />
			<ValueEntry language="de" title="Timing" info="Hier Timings eintragen" />
		</ValueSet>
		<ValueSet ident="logoPosition" type="dropdown" defaultValue="0">
			<ValueEntry language="en" title="Logo position" info="please choose" isDefault="true" />
			<ValueEntry language="de" title="Logo Position" info="Wählen Sie aus" />
			<ValueSet ident="0;0" type="short_text">
				<ValueEntry language="en" title="Top-Left" isDefault="true" />
				<ValueEntry language="de" title="Oben-Links" />
			</ValueSet>
			<ValueSet ident="10;10" type="short_text">
				<ValueEntry language="en" title="Top 10-Left 10" isDefault="true" />
				<ValueEntry language="de" title="Oben 10-Links 10" />
			</ValueSet>
			<ValueSet ident="0;20" type="short_text">
				<ValueEntry language="en" title="Top 20-Left" isDefault="true" />
				<ValueEntry language="de" title="Oben 20-Links" />
			</ValueSet>
		</ValueSet>
		<ValueSet ident="displayDate" type="date">
			<ValueEntry language="en" title="Showing date" info="Please choose" isDefault="true" />
			<ValueEntry language="de" title="Anzeige Datum" info="Wählen Sie aus" />
		</ValueSet>
		<ValueSet ident="displayTime" type="time">
			<ValueEntry language="en" title="Showing time" info="Please choose" isDefault="true" />
			<ValueEntry language="de" title="Anzeige Zeit" info="Wählen Sie aus" />
		</ValueSet>
        <ValueSet ident="promoAF" type="animation_factory">
            <ValueEntry language="en" title="Linked AF" info="Example of a linked AF" isDefault="true"/>
            <ValueEntry language="de" title="Verlinkte Animation" info="Beispiel einer verlinkten Animation"/>
        </ValueSet>
	</MovieVars>
	<DataSets>
		<ValueSet ident="manufacturer" type="short_text" defaultValue="Hallo Welt">
			<ValueEntry language="en" title="Manufacturere" info="The name of the manufacturer" isDefault="true" />
			<ValueEntry language="de" title="Hersteller" info="Der Name des Herstellers" />
		</ValueSet>
		<ValueSet ident="articleTitle" type="short_text">
			<ValueEntry language="en" title="Title" info="The name of the article" isDefault="true" />
			<ValueEntry language="de" title="Bezeichnung" info="Bezeichnung des Artikels" />
		</ValueSet>
		<ValueSet ident="articleDescr" type="long_text" defaultValue="Hallo Welt2">
			<ValueEntry language="en" title="Description" info="Description of the Article" isDefault="true" />
			<ValueEntry language="de" title="Beschreibung" info="Beschreibung des Article Factorys" />
		</ValueSet>
		<ValueSet ident="textColor" type="color" defaultValue="C1BBAF">
			<ValueEntry language="en" title="Text color" info="Color of the description" isDefault="true" />
			<ValueEntry language="de" title="Text Farbe" info="Farbe der Bezeichnung" />
		</ValueSet>
		<ValueSet ident="articleImg" type="image" defaultValue="32144.jpg">
			<ValueEntry language="en" title="Article's image" info="Choice of the article's image" isDefault="true" />
			<ValueEntry language="de" title="Artikel Abbildung" info="Auswahl des Artikel-Bildes" />
		</ValueSet>
		<ValueSet ident="advertiseVideo" type="video" defaultValue="32144.flv">
			<ValueEntry language="en" title="Advertising video" info="Advertising video as .flv" isDefault="true" />
			<ValueEntry language="de" title="advertiseVideo" info="Werbevidio als .flv" />
		</ValueSet>
		<ValueSet ident="snowEffect" type="boolean" defaultValue="true"  isHidden="true">
			<ValueEntry language="en" title="Snow effect" info="Activate snow effect" isDefault="true" />
			<ValueEntry language="de" title="Schneeeffekt" info="Schneeeffekt aktivieren" />
		</ValueSet>
		<ValueSet ident="nrSnowflakes" type="number" defaultValue="1"  isReadOnly="true">
			<ValueEntry language="en" title="Snowflakes" info="Number of snowflakes" isDefault="true" />
			<ValueEntry language="de" title="Schneeflocken" info="Anzahl der Schneeflocken" />
		</ValueSet>
		<ValueSet ident="timing" type="timing">
			<ValueEntry language="en" title="Timing" info="Create Timings here" isDefault="true" />
			<ValueEntry language="de" title="Timing" info="Hier Timings eintragen" />
		</ValueSet>
		<ValueSet ident="imageScale" type="dropdown" defaultValue="100">
			<ValueEntry language="en" title="Image scaling" info="please choose" isDefault="true" />
			<ValueEntry language="de" title="Bildskalierung" info="Wählen Sie aus" />
			<ValueSet ident="20" type="short_text">
				<ValueEntry language="en" title="20 %" isDefault="true" />
			</ValueSet>
			<ValueSet ident="40" type="short_text">
				<ValueEntry language="en" title="40 %" isDefault="true" />
			</ValueSet>
			<ValueSet ident="60" type="short_text">
				<ValueEntry language="en" title="60 %" isDefault="true" />
			</ValueSet>
			<ValueSet ident="80" type="short_text">
				<ValueEntry language="en" title="80 %" isDefault="true" />
			</ValueSet>
			<ValueSet ident="100" type="short_text">
				<ValueEntry language="en" title="100 %" isDefault="true" />
			</ValueSet>
		</ValueSet>
		<ValueSet ident="showDate" type="date">
			<ValueEntry language="en" title="Showing date" info="Please choose" isDefault="true" />
			<ValueEntry language="de" title="Anzeige Datum" info="Wählen Sie aus" />
		</ValueSet>
		<ValueSet ident="showTime" type="time">
			<ValueEntry language="en" title="Showing time" info="Please choose" isDefault="true" />
			<ValueEntry language="de" title="Anzeige Zeit" info="Wählen Sie aus" />
		</ValueSet>
	</DataSets>
</InputAF>
